
addons:
  postgresql: 9.6
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.4.2
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
services:
  - redis-server